apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: dep-frontend-hands-on
  labels:
    app: dep-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-frontend 
  template: 
    metadata:
      labels:
        app: pod-frontend 
    spec:
      containers:
      - name: frontend
        image: ricardoandre97/frontend-k8s-hands-on:v1
        imagePullPolicy: IfNotPresent

---
apiVersion: v1  
kind: Service
metadata:
  name: sv-frontend-k8s-hands-on
  labels:
    app: sv-frontend
spec:
  type: NodePort
  selector: 
    app: pod-frontend
  ports:
    - protocol: TCP
      port: 80 # Donde se escucha el servicio
      targetPort: 80 # Donde se comunican los pods
  