apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: dep-backend-hands-on
  labels:
    app: dep-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pod-backend 
  template: 
    metadata:
      labels:
        app: pod-backend 
    spec:
      containers:
      - name: backend
        image: ricardoandre97/backend-k8s-hands-on:v2
        imagePullPolicy: IfNotPresent

---
apiVersion: v1 
kind: Service
metadata:
  name: sv-backend-k8s-hands-on
  labels:
    app: sv-backend
spec:
  selector: 
    app: pod-backend
  ports:
    - protocol: TCP
      port: 80 # Donde se escucha el servicio
      targetPort: 9090 # Donde se comunican los pods
  